# Generated by Django 5.2.1 on 2025-07-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='avif_icon',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='advantages/avif/'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='avif_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/avif/'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='webp_icon',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='advantages/webp/'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='webp_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/webp/'),
        ),
        migrations.AddField(
            model_name='productshowcaseitem',
            name='avif_background_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='showcase/avif/'),
        ),
        migrations.AddField(
            model_name='productshowcaseitem',
            name='avif_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/avif/'),
        ),
        migrations.AddField(
            model_name='productshowcaseitem',
            name='webp_background_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='showcase/webp/'),
        ),
        migrations.AddField(
            model_name='productshowcaseitem',
            name='webp_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/webp/'),
        ),
        migrations.AddField(
            model_name='service',
            name='avif_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/avif/'),
        ),
        migrations.AddField(
            model_name='service',
            name='webp_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/webp/'),
        ),
    ]
