# Generated by Django 4.2.7 on 2025-07-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_advantage_avif_icon_advantage_avif_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advantage',
            name='avif_image',
        ),
        migrations.RemoveField(
            model_name='advantage',
            name='webp_image',
        ),
        migrations.RemoveField(
            model_name='productshowcaseitem',
            name='avif_image',
        ),
        migrations.RemoveField(
            model_name='productshowcaseitem',
            name='webp_image',
        ),
        migrations.AlterField(
            model_name='service',
            name='avif_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='services/avif/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='webp_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='services/webp/'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['slug'], name='api_service_slug_142ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['created_at'], name='api_service_created_97daaf_idx'),
        ),
    ]
